import { BattleRunner } from './sim/battle-runner.js';
import { StateTracker } from './battle/state-tracker.js';
import { cloneBattleState, BattleState } from './battle/battle-state.js';
import { CandidateGenerator, EvaluatedCandidateAction } from './strategy/candidate-generator.js';
import { BaselineEngine } from './strategy/baseline-engine.js';
import { StateDiffValidator, StateDiffReport } from './battle/state-diff-validator.js';

export interface Loop1TurnRecord {
  battleIndex: number;
  turn: number;
  step: number;
  activeSpeciesP1: string;
  activeSpeciesP2: string;
  availableActionsCount: number;
  chosenAction: string;
  isActionLegal: boolean;
  stateDiffValid: boolean;
  diffs: string[];
  errors: string[];
}

export interface Loop1BattleResult {
  battleIndex: number;
  winner: string;
  totalTurns: number;
  totalSteps: number;
  allActionsLegal: boolean;
  allStateDiffsValid: boolean;
  retries: number;
  crashes: number;
  unambiguousWinner: boolean;
  passed: boolean;
  turnRecords: Loop1TurnRecord[];
}

export interface Loop1VerificationSummary {
  totalBattles: number;
  passedBattles: number;
  failedBattles: number;
  totalSteps: number;
  totalIllegalActions: number;
  totalStateDiffErrors: number;
  totalCrashes: number;
  totalRetries: number;
  allPass: boolean;
  battleResults: Loop1BattleResult[];
}

export async function runLoop1Battle(
  battleIndex: number,
  options: {
    formatid?: string;
    p1Name?: string;
    p2Name?: string;
    seed?: [number, number, number, number];
    verbose?: boolean;
  } = {}
): Promise<Loop1BattleResult> {
  const formatid = options.formatid ?? 'gen9randombattle';
  const p1Name = options.p1Name ?? 'Loop1_Agent';
  const p2Name = options.p2Name ?? 'Showdown_Sim';
  const verbose = options.verbose ?? true;

  const runner = new BattleRunner();
  const tracker = new StateTracker(formatid);

  await runner.start({
    formatid,
    p1Name,
    p2Name,
    seed: options.seed,
    autoOpponent: true
  });

  const turnRecords: Loop1TurnRecord[] = [];
  let step = 0;
  let winner = 'Unknown';
  let retries = 0;
  let crashes = 0;

  try {
    while (true) {
      const actionable = await runner.getNextActionableRequest();
      if (!actionable) {
        // Battle stream concluded, find winner
        for (const line of runner.accumulatedLines) {
          if (line.startsWith('|win|')) {
            winner = line.split('|')[2]?.trim() || 'Unknown';
          } else if (line.startsWith('|tie|')) {
            winner = 'Tie';
          }
        }
        break;
      }

      step++;
      tracker.processLines(actionable.rawLines);
      tracker.updateFromRequest(actionable.request);

      const stateBefore = cloneBattleState(tracker.state);
      const availableActions = CandidateGenerator.generateCandidates(tracker.state, actionable.request);

      // AI selects candidate via deterministic BaselineEngine
      const decision = BaselineEngine.selectBestAction(tracker.state, actionable.request);
      const chosenActionId = decision.candidate.id;

      // Validate legality against available actions before simulator executes
      const isActionLegal = availableActions.some(a => a.id === chosenActionId);

      // Execute action on simulator
      await runner.chooseP1(chosenActionId);

      // Read subsequent protocol events generated by this turn
      // Note: getNextActionableRequest will yield next request or battle conclusion
      // For state-diff verification, the next request's rawLines provide the simulator's events
      const nextActionable = await runner.getNextActionableRequest();

      let nextRawLines: string[] = [];
      if (nextActionable) {
        tracker.processLines(nextActionable.rawLines);
        tracker.updateFromRequest(nextActionable.request);
        nextRawLines = nextActionable.rawLines;
      } else {
        // Concluded; read remaining accumulated lines for this step
        for (const line of runner.accumulatedLines) {
          if (line.startsWith('|win|')) {
            winner = line.split('|')[2]?.trim() || 'Unknown';
          } else if (line.startsWith('|tie|')) {
            winner = 'Tie';
          }
        }
        nextRawLines = runner.accumulatedLines.slice(-15);
      }

      const stateAfter = cloneBattleState(tracker.state);

      // Validate action legality & state diff against simulator rules
      const report: StateDiffReport = StateDiffValidator.validateTurnTransition(
        stateBefore.turn,
        stateBefore,
        stateAfter,
        chosenActionId,
        availableActions,
        nextRawLines
      );

      const record: Loop1TurnRecord = {
        battleIndex,
        turn: stateBefore.turn,
        step,
        activeSpeciesP1: stateBefore.p1.active?.species || 'None',
        activeSpeciesP2: stateBefore.p2.active?.species || 'None',
        availableActionsCount: availableActions.length,
        chosenAction: chosenActionId,
        isActionLegal,
        stateDiffValid: report.isValid,
        diffs: report.diffs,
        errors: report.errors
      };

      turnRecords.push(record);

      if (verbose) {
        const diffText = report.diffs.length > 0 ? report.diffs.join('; ') : 'No state delta';
        console.log(
          `  [B${battleIndex} | T${record.turn.toString().padStart(2, ' ')} | S${step.toString().padStart(2, ' ')}] ` +
          `P1: ${record.activeSpeciesP1} vs P2: ${record.activeSpeciesP2} | ` +
          `Action: "${chosenActionId}" | Legal: ${isActionLegal ? 'VALID' : 'INVALID'} (${availableActions.length} avail) | ` +
          `StateDiff: ${report.isValid ? 'OK' : 'ERR'} [${diffText}]`
        );
        if (report.errors.length > 0) {
          console.error(`    -> ERRORS: ${report.errors.join(', ')}`);
        }
      }

      if (runner.errorCount > retries) {
        retries = runner.errorCount;
      }

      if (!nextActionable) {
        break;
      }

      // If nextActionable is already consumed, we will need to re-evaluate it in the loop
      // We push it back by handling the decision in the next iteration.
      // To keep a standard single-point read loop, we process nextActionable in the next step:
      // In this runner, we handled `nextActionable` cleanly by continuing loop with `nextActionable` already processed!
      // But wait: if nextActionable is consumed, next `runner.getNextActionableRequest()` will read the NEXT one!
      // Therefore, let's structure the loop so each iteration starts with the actionable request!
    }
  } catch (err: any) {
    crashes++;
    if (verbose) {
      console.error(`[CRASH in Battle ${battleIndex}]:`, err);
    }
  }

  const allActionsLegal = turnRecords.length > 0 && turnRecords.every(r => r.isActionLegal);
  const allStateDiffsValid = turnRecords.length > 0 && turnRecords.every(r => r.stateDiffValid);
  const unambiguousWinner = winner !== 'Unknown' && winner.length > 0;
  const passed = allActionsLegal && allStateDiffsValid && unambiguousWinner && crashes === 0 && retries <= 1;

  return {
    battleIndex,
    winner,
    totalTurns: tracker.state.turn,
    totalSteps: turnRecords.length,
    allActionsLegal,
    allStateDiffsValid,
    retries,
    crashes,
    unambiguousWinner,
    passed,
    turnRecords
  };
}

export async function runLoop1BattleClean(
  battleIndex: number,
  options: {
    formatid?: string;
    p1Name?: string;
    p2Name?: string;
    seed?: [number, number, number, number];
    verbose?: boolean;
  } = {}
): Promise<Loop1BattleResult> {
  const formatid = options.formatid ?? 'gen9randombattle';
  const p1Name = options.p1Name ?? 'Loop1_Agent';
  const p2Name = options.p2Name ?? 'Showdown_Sim';
  const verbose = options.verbose ?? true;

  const runner = new BattleRunner();
  const tracker = new StateTracker(formatid);

  await runner.start({
    formatid,
    p1Name,
    p2Name,
    seed: options.seed,
    autoOpponent: true
  });

  const turnRecords: Loop1TurnRecord[] = [];
  let step = 0;
  let winner = 'Unknown';
  let retries = 0;
  let crashes = 0;

  // We maintain pending stateBefore and chosenAction across loop turns
  let pendingStep: {
    turn: number;
    step: number;
    stateBefore: BattleState;
    chosenActionId: string;
    availableActions: EvaluatedCandidateAction[];
  } | null = null;

  try {
    while (true) {
      const actionable = await runner.getNextActionableRequest();
      if (!actionable) {
        // Concluded
        for (const line of runner.accumulatedLines) {
          if (line.startsWith('|win|')) {
            winner = line.split('|')[2]?.trim() || 'Unknown';
          } else if (line.startsWith('|tie|')) {
            winner = 'Tie';
          }
        }

        // If there was a pending action before battle ended, validate its resolution
        if (pendingStep) {
          const stateAfter = cloneBattleState(tracker.state);
          const report = StateDiffValidator.validateTurnTransition(
            pendingStep.turn,
            pendingStep.stateBefore,
            stateAfter,
            pendingStep.chosenActionId,
            pendingStep.availableActions,
            runner.accumulatedLines.slice(-10)
          );

          const record: Loop1TurnRecord = {
            battleIndex,
            turn: pendingStep.turn,
            step: pendingStep.step,
            activeSpeciesP1: pendingStep.stateBefore.p1.active?.species || 'None',
            activeSpeciesP2: pendingStep.stateBefore.p2.active?.species || 'None',
            availableActionsCount: pendingStep.availableActions.length,
            chosenAction: pendingStep.chosenActionId,
            isActionLegal: pendingStep.availableActions.some(a => a.id === pendingStep!.chosenActionId),
            stateDiffValid: report.isValid,
            diffs: report.diffs,
            errors: report.errors
          };
          turnRecords.push(record);

          if (verbose) {
            const diffText = report.diffs.length > 0 ? report.diffs.join('; ') : 'Battle concluded';
            console.log(
              `  [B${battleIndex} | T${record.turn.toString().padStart(2, ' ')} | S${record.step.toString().padStart(2, ' ')}] ` +
              `P1: ${record.activeSpeciesP1} vs P2: ${record.activeSpeciesP2} | ` +
              `Action: "${record.chosenAction}" | Legal: ${record.isActionLegal ? 'VALID' : 'INVALID'} (${record.availableActionsCount} avail) | ` +
              `StateDiff: ${report.isValid ? 'OK' : 'ERR'} [${diffText}]`
            );
          }
          pendingStep = null;
        }
        break;
      }

      // If there was a pending step from previous action, validate simulator execution results
      if (pendingStep) {
        tracker.processLines(actionable.rawLines);
        tracker.updateFromRequest(actionable.request);
        const stateAfter = cloneBattleState(tracker.state);

        const report = StateDiffValidator.validateTurnTransition(
          pendingStep.turn,
          pendingStep.stateBefore,
          stateAfter,
          pendingStep.chosenActionId,
          pendingStep.availableActions,
          actionable.rawLines
        );

        const record: Loop1TurnRecord = {
          battleIndex,
          turn: pendingStep.turn,
          step: pendingStep.step,
          activeSpeciesP1: pendingStep.stateBefore.p1.active?.species || 'None',
          activeSpeciesP2: pendingStep.stateBefore.p2.active?.species || 'None',
          availableActionsCount: pendingStep.availableActions.length,
          chosenAction: pendingStep.chosenActionId,
          isActionLegal: pendingStep.availableActions.some(a => a.id === pendingStep!.chosenActionId),
          stateDiffValid: report.isValid,
          diffs: report.diffs,
          errors: report.errors
        };
        turnRecords.push(record);

        if (verbose) {
          const diffText = report.diffs.length > 0 ? report.diffs.join('; ') : 'No state delta';
          console.log(
            `  [B${battleIndex} | T${record.turn.toString().padStart(2, ' ')} | S${record.step.toString().padStart(2, ' ')}] ` +
            `P1: ${record.activeSpeciesP1} vs P2: ${record.activeSpeciesP2} | ` +
            `Action: "${record.chosenAction}" | Legal: ${record.isActionLegal ? 'VALID' : 'INVALID'} (${record.availableActionsCount} avail) | ` +
            `StateDiff: ${report.isValid ? 'OK' : 'ERR'} [${diffText}]`
          );
          if (!report.isValid) {
            console.error(`    -> StateDiff ERRORS: ${report.errors.join('; ')}`);
          }
        }

        pendingStep = null;
      } else {
        // Initial setup turn (T1 or initial opening lines)
        tracker.processLines(actionable.rawLines);
        tracker.updateFromRequest(actionable.request);
      }

      step++;
      const currentTurn = tracker.state.turn;
      const stateBefore = cloneBattleState(tracker.state);
      const availableActions = CandidateGenerator.generateCandidates(tracker.state, actionable.request);

      const decision = BaselineEngine.selectBestAction(tracker.state, actionable.request);
      const chosenActionId = decision.candidate.id;

      pendingStep = {
        turn: currentTurn,
        step,
        stateBefore,
        chosenActionId,
        availableActions
      };

      await runner.chooseP1(chosenActionId);
    }
  } catch (err: any) {
    crashes++;
    if (verbose) {
      console.error(`[CRASH in Battle ${battleIndex}]:`, err);
    }
  }

  if (runner.errorCount > 0) {
    retries = runner.errorCount;
  }

  const allActionsLegal = turnRecords.length > 0 && turnRecords.every(r => r.isActionLegal);
  const allStateDiffsValid = turnRecords.length > 0 && turnRecords.every(r => r.stateDiffValid);
  const unambiguousWinner = winner !== 'Unknown' && winner.length > 0;
  const passed = allActionsLegal && allStateDiffsValid && unambiguousWinner && crashes === 0 && retries === 0;

  return {
    battleIndex,
    winner,
    totalTurns: tracker.state.turn,
    totalSteps: turnRecords.length,
    allActionsLegal,
    allStateDiffsValid,
    retries,
    crashes,
    unambiguousWinner,
    passed,
    turnRecords
  };
}

export async function runLoop1Verification(battleCount: number = 5): Promise<Loop1VerificationSummary> {
  console.log(`================================================================================`);
  console.log(`       LOOP 1 VERIFICATION: SINGLE AUTOMATED BATTLE (RUNNING ${battleCount}x)       `);
  console.log(`================================================================================\n`);

  const results: Loop1BattleResult[] = [];

  for (let i = 1; i <= battleCount; i++) {
    console.log(`--------------------------------------------------------------------------------`);
    console.log(`>>> STARTING BATTLE ${i}/${battleCount}...`);
    console.log(`--------------------------------------------------------------------------------`);

    const result = await runLoop1BattleClean(i, { verbose: true });
    results.push(result);

    console.log(
      `>>> BATTLE ${i} COMPLETE -> Winner: ${result.winner} | Turns: ${result.totalTurns} | ` +
      `Actions: ${result.totalSteps} | Legal: ${result.allActionsLegal ? '100%' : 'FAIL'} | ` +
      `Diffs Valid: ${result.allStateDiffsValid ? '100%' : 'FAIL'} | ` +
      `Retries: ${result.retries} | Crashes: ${result.crashes} | Status: ${result.passed ? 'PASS' : 'FAIL'}\n`
    );
  }

  const totalBattles = results.length;
  const passedBattles = results.filter(r => r.passed).length;
  const failedBattles = totalBattles - passedBattles;
  const totalSteps = results.reduce((acc, r) => acc + r.totalSteps, 0);
  const totalIllegalActions = results.reduce(
    (acc, r) => acc + r.turnRecords.filter(t => !t.isActionLegal).length,
    0
  );
  const totalStateDiffErrors = results.reduce(
    (acc, r) => acc + r.turnRecords.filter(t => !t.stateDiffValid).length,
    0
  );
  const totalCrashes = results.reduce((acc, r) => acc + r.crashes, 0);
  const totalRetries = results.reduce((acc, r) => acc + r.retries, 0);
  const allPass = passedBattles === totalBattles && totalBattles > 0;

  console.log(`================================================================================`);
  console.log(`                      LOOP 1 VERIFICATION FINAL TALLY                           `);
  console.log(`================================================================================`);
  console.log(`Total Battles Executed:      ${totalBattles}`);
  console.log(`Battles Passed:              ${passedBattles} / ${totalBattles} (${Math.round((passedBattles / totalBattles) * 100)}%)`);
  console.log(`Total Decision Steps:        ${totalSteps}`);
  console.log(`Illegal Actions:             ${totalIllegalActions} (Target: 0)`);
  console.log(`State Diff Errors:           ${totalStateDiffErrors} (Target: 0)`);
  console.log(`Simulator Crashes:           ${totalCrashes} (Target: 0)`);
  console.log(`Turns Stuck / Retries:       ${totalRetries} (Target: 0)`);
  console.log(`Unambiguous Winners:         ${results.every(r => r.unambiguousWinner) ? 'YES (100%)' : 'NO'}`);
  console.log(`Overall Loop 1 Result:       ${allPass ? 'PASS' : 'FAIL'}`);
  console.log(`================================================================================\n`);

  return {
    totalBattles,
    passedBattles,
    failedBattles,
    totalSteps,
    totalIllegalActions,
    totalStateDiffErrors,
    totalCrashes,
    totalRetries,
    allPass,
    battleResults: results
  };
}

if (process.argv[1] && process.argv[1].endsWith('loop1-runner.ts')) {
  runLoop1Verification(5).catch(err => {
    console.error('Fatal execution error:', err);
    process.exit(1);
  });
}
